server:
  port: 20400

spring:
  application:
    name: delivery-service

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

ai:
  gemini:
    api-key: ${GOOGLE_API_KEY}
    base-url: https://generativelanguage.googleapis.com/v1
    default-model: ${GOOGLE_MODEL}
