server:
  port: 8080

spring:
  application:
    name: gateway-service
  data:
    redis:
      host: localhost
      port: 6379
      password: systempass
      database: 0
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/v1/users/**

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/v1/orders/**

            - id: hub-service
              uri: lb://HUB-SERVICE
              predicates:
                - Path=/v1/hubs/**, /v1/hub-routes/**, /internal/v1/hubs/**

            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/v1/products/**, /internal/v1/products/**


            - id: delivery-service
              uri: lb://DELIVERY-SERVICE
              predicates:
                - Path=/v1/delivery/**, /v1/ai/**

            - id: vendor-service
              uri: lb://VENDOR-SERVICE
              predicates:
                - Path=/v1/vendors/**, /internal/v1/vendors/**

            - id: slack-service
              uri: lb://SLACK-SERVICE
              predicates:
                - Path=/v1/slacks/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: user-service
        url: http://localhost:20000/v3/api-docs

      - name: order-service
        url: http://localhost:20100/v3/api-docs

      - name: hub-service
        url: http://localhost:20200/v3/api-docs

      - name: product-service
        url: http://localhost:20300/v3/api-docs

      - name: delivery-service
        url: http://localhost:20400/v3/api-docs

      - name: vendor-service
        url: http://localhost:20500/v3/api-docs

      - name: slack-service
        url: http://localhost:20600/v3/api-docs

jwt:
  secret: ${JWT_KEY}
