server:
  port: 20600

spring:
  application:
    name: slack-service

  datasource:
    url: jdbc:postgresql://localhost:5432/slack_db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

slack:
  bot:
    token: ${SLACK_BOT_TOKEN}
