server:
  port: 20000

spring:
  application:
    name: user-service
  data:
    redis:
      host: localhost
      port: 6379
      password: systempass
      database: 0

  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

jwt:
  secret: ${JWT_KEY}
  access-expiration: 60m
  refresh-expiration: 7d
